### ISSUE TITLE
Hoàn thiện chức năng trang Login & register

### ISSUE THREAD

**Issue by khongtinhao** [vannt010391/SalesPage#19]

**Comment by vannt010391** [comment]
@khongtinhao Em mô tả chức năng này nhé.
Thông tin trang Register gồm những gì?
Khi đăng ký có cần xác nhận qua email không?
Đăng nhập gồm những thông tin gì?

**Comment by khongtinhao** [comment]
Thông tin trang Register sẽ có:
Email, tên đăng nhập, mật khẩu, nhập lại mật khẩu 
dự kiến là làm xác nhận qua email nhưng chưa tìm được hướng giải quyết
Đăng nhập gồm tên đăng nhập và mật khẩu, sau khi đăng nhập thành công sẽ chuyển sang trang chủ

**Comment by vannt010391** [comment]
> Thông tin trang Register sẽ có:
> Email, tên đăng nhập, mật khẩu, nhập lại mật khẩu
> dự kiến là làm xác nhận qua email nhưng chưa tìm được hướng giải quyết
> Đăng nhập gồm tên đăng nhập và mật khẩu, sau khi đăng nhập thành công sẽ chuyển sang trang chủ

**Comment by vannt010391** [comment]
1. Register gồm các thông tin: Email, Username, Password, Retype Password . 1 email chỉ được đăng ký 1 tài khoản
2. Khi người dùng đăng ký, người dùng sẽ nhận được email xác nhận. Có 2 cách để xác nhận ở đây:

- Cách 1: Xác nhận qua đường link được đính kèm qua email
- Cách 2: Xác nhận bằng cách nhập PassCode

3. Thông tin đăng nhập: User name và password. Khi đăng nhập thành công sẽ chuyển tiếp sang trang chủ. Thiết lập quyền cho user là Authenticated User
4. Hỗ trợ tính năng quên mật khẩu. 
5. Sau khi người dùng có tài khoản trên hệ thống, họ có quyền làm gì?
