### ISSUE TITLE
Hoàn thiện trang Tin Tức - Blog

### ISSUE THREAD

**Issue by vannt010391** [vannt010391/SalesPage#3]

**Comment by Baotranvt12** [comment]
Tìm kiếm tin tức
Tạo diễn đàn cho người dùng nhập tin tức
Và 1 bên là tin tức mới nhất

**Comment by vannt010391** [comment]
Hiển thị:
- Trang Blog/Tin Tức: Hiển thị danh sách bài viết/tin tức. Hiển thị bài viết mới nhất nằm ở cuối cùng/đầu tiên
- Trang Blog Details: Link từ trang blog. Hiển thị chi tiết bài viết: Tên bài viết, hình ảnh, người tạo, ngày tạo, keywords, bài viết liên quan...
-
Chức năng:
- Tìm kiếm
- Sort: bài viết mới nhất, theo tên
- Phân trang
- Hiển thị bài viết liên quan
