### ISSUE TITLE
Hoàn thiện trang Sản phẩm & Quà tặng cao cấp (Product)

### ISSUE THREAD

**Issue by vannt010391** [vannt010391/SalesPage#4]

**Comment by tuyet313** [comment]
Trang sản phẩm:
  - Hiển thị những thông tin của sản phẩm theo từng danh mục tương ứng.
  - Thông tin sản phẩm thể hiện gồm có hình ảnh, tên sản phẩm, giá tiền và button order
  - Khi click vào sản phẩm sẽ hiển thị ra một trang mới, hiển thị những thông tin chi tiết về sản phẩm và gợi ý một vài sản phẩm khác
  - Khi bấm vào order sản phẩm sẽ được thêm vào danh sách mua hàng

Trang quà tặng cao cấp:
  - Hiển thị các gói quà tặng cao cấp được mua trước
  - Khi click vào gói quà tặng sẽ hiện ra thông tin chi tiết

**Comment by vannt010391** [comment]
Chức năng:
- Tìm kiếm sản phẩm
- Phân trang

**Comment by tuyet313** [comment]
Dự kiến ngày hoàn thành: trước chủ nhật (23/05/2021)
